name: dalil_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.3
  permission_handler: ^10.2.0
  #---------
  font_awesome_flutter: ^10.4.0
  hexcolor: ^3.0.1
  buttons_tabbar: ^1.3.6
  image_picker: ^0.8.6+3
  fancy_shimmer_image: ^2.0.2
  tab_indicator_styler: ^2.0.0
  flutter_rating_bar: ^4.0.1
  #----------
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.7
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/pics/


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

