// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKgVbOmFgudh_GxObp2zRspHro1SJLeQ',
    appId: '1:106606140790:web:c8cd178161740c22bbee57',
    messagingSenderId: '106606140790',
    projectId: 'dalil-74c22',
    authDomain: 'dalil-74c22.firebaseapp.com',
    storageBucket: 'dalil-74c22.appspot.com',
    measurementId: 'G-Y3VSDNFHEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTLxBnSIPPijkQygqd2jui2KZ-6KZ49Q',
    appId: '1:106606140790:android:bdaf5da5d833d2c9bbee57',
    messagingSenderId: '106606140790',
    projectId: 'dalil-74c22',
    storageBucket: 'dalil-74c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSiTCphY7pWl7vjE5f12snpYJexzbQXPk',
    appId: '1:106606140790:ios:e892df7eefc8adc6bbee57',
    messagingSenderId: '106606140790',
    projectId: 'dalil-74c22',
    storageBucket: 'dalil-74c22.appspot.com',
    iosClientId: '106606140790-0nbo6gurhg9rh2sbubt3aqa1d69o1g0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSiTCphY7pWl7vjE5f12snpYJexzbQXPk',
    appId: '1:106606140790:ios:e892df7eefc8adc6bbee57',
    messagingSenderId: '106606140790',
    projectId: 'dalil-74c22',
    storageBucket: 'dalil-74c22.appspot.com',
    iosClientId: '106606140790-0nbo6gurhg9rh2sbubt3aqa1d69o1g0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalilApp',
  );
}
